### ISSUE TITLE
Most of the examples fail to launch with MSVC2019 + Qt5 environment

### ISSUE THREAD

**Issue by waka4g** [jkriege2/JKQtPlotter#116]
After successfully building this excellent library using CMake, following the comprehensive documentation provided, I attempted to run the example applications. However, most of these applications fail to launch. (Exceptions are "jkqtptest_jkqtmathtext_simpletest.exe" and "jkqtptest_jkqtmathtext_test.exe". I was able to launch these two applications.)

### Environment
- MSVC 2019 (16.11.33)
- Qt 5.15.2 msvc2019_64
- CMake 3.27.4
- Windows 10 22H2
- JKQtPlotter v4.0.2

### Actual Behavior
After a successful build, tried to launch the example applications.
- Double-clicked on the application icon. No response or error message.
- Attempting to launch the applications from the command prompt. Again, no response or error message.
- Exceptions are "jkqtptest_jkqtmathtext_test.exe" and "jkqtptest_jkqtmathtext_simpletest.exe". I was able to launch these two applications.

### Additional Information
When attempting to launch the "jkqtptest_simpletest.exe" application via the debugger, an Access Violation error occurs. The debugger indicates that this issue arises at line 458 in the file "jkqtmathtexttools.cpp". A screenshot of the debugger output (sorry but in Japanese) is attached for reference.

Any guidance or suggestions to resolve this issue would be highly appreciated. 

![image](https://github.com/jkriege2/JKQtPlotter/assets/37063675/9a5eb119-8f66-40a6-95d8-74d095458ecd)

**Comment by jkriege2** [comment]
Hi!

yes, I can confirm the problem ... very stange ... I don't see it with Qt6 though ... do you need to rely on Qt 5?

Best,
JAN

**Comment by waka4g** [comment]
> do you need to rely on Qt 5?
No, I don't. It's great news for me that this issue does not occur with Qt6. 
I will take this opportunity to migrate Qt6!

Thank you very much.

**Comment by jkriege2** [comment]
... I have to correct myself: interestingly this bug does not appear in Qt6 or gcc ... because I ound a problem in the code you screenshot above: Inside the functor a line JKQTMathTextFontSpecifier fontSpec; was mising ... so I don't know at all, why this code compiled, as the outside fontSpec instance should not be accessibly without a capture-clause ... ver strange ... anyways, I fixed the problem and the current master should be fine also with Qt5 and MSVC (at  least it worked for me).

See https://github.com/jkriege2/JKQtPlotter/commit/ef07a02e9bb0a1697c7b6f96316c243980b46100 for the fix
