### ISSUE TITLE
Crash in 4.0.2

### ISSUE THREAD

**Issue by doug1234** [jkriege2/JKQtPlotter#123]
The function JKQTMathTextFontSpecifier JKQTMathTextFontSpecifier::getAppFontSFFamilies() crashes if it gets called in 4.0.2.  This is due to a missing variable definition.  Looks like it has been fixed in master.  Should there be a 4.0.3?

**Comment by jkriege2** [comment]
Hmmm ... it seems that went pear-shaped ... 4.0.2 seems not to be a tag onto the 4.0.0. branch, but I erroneously tagged the master .... so that function was never meant to be in that tag.

I think I will have to think about starting to tag 5.0.0 version ... I got a lot of the features that I wished for that release by now ...

Until I can create a 5.0.0 branch ... could you work with master?

**Comment by doug1234** [comment]
Maybe I should just use the 4.0.1 tag then.  Should that one be safe?

**Comment by jkriege2** [comment]
If you don't need this fix: https://github.com/jkriege2/JKQtPlotter/pull/115 you can use 4.0.1

**Comment by doug1234** [comment]
I really just use the basic stuff.  I don't think that fix is necessary.  I could wait for 5.0 to update.

**Comment by jkriege2** [comment]
I just added a release v4.0.3 which should again be on the correct  4.0.0 branch ... does this help (unless you use the more feature-rich 5.0/master anyways)

**Comment by doug1234** [comment]
Thanks.  Will start using that version shortly.
