### ISSUE TITLE
Undefined behaviour in jkqtp_format

### ISSUE THREAD

**Issue by Makis42** [jkriege2/JKQtPlotter#43]
The utility function 'std::string jkqtp_format(const std::string& templ, ...)' uses a reference 'templ' which doesn't work at all with va_start. Every call gets a different result.

My environment: Windows 10, VS2017

**Comment by jkriege2** [comment]
Hi!

thanks for reporting ... and sorry for the long wait ...

I didn't know that ... since there is no solution in C++11 that I know of (short of having the format-string as copy-by-value), I fixed this (b22b4ca9356e28e2d3e3486830df08260ad11a1f) by adding 4 overloaded template-functions ... now it works for 1-4 arguments, which is enough for the purpose of the library ... 

In general, there is a better solution in C++17 with argument packs (I think) ... but I don't want to enforce C++17 for this lib.

Best,
JAN
