### ISSUE TITLE
Failure on Windows

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#44]
I am trying to update JKQtPlotter in Conda:

https://github.com/conda-forge/jkqtplotter-feedstock/pull/4

and things build on Linux and macOS, but I am having some issue on Windows:

https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/179691/logs/25

and I don't quite understand from the log where the error happens. The build seems to simply stop but for no reason:
```
2020-06-30T16:15:07.8000101Z [21/81] Building CXX object lib\jkqtcommon\CMakeFiles\JKQTCommonSharedLib.dir\jkqtpstatgrouped.cpp.obj
2020-06-30T16:15:07.8001594Z cl : Command line warning D9002 : ignoring unknown option '-G='
2020-06-30T16:15:07.8522381Z [22/81] Linking CXX shared library output\JKQTCommonSharedLib_Release.dll
2020-06-30T16:15:07.8523995Z FAILED: output/JKQTCommonSharedLib_Release.dll lib/jkqtcommon/JKQTCommonSharedLib_Release.lib 
```

@jkriege2 do you have any ideas what the problem could be?

**Comment by jkriege2** [comment]
Hi!

I'm not really sure, where that -G= comes from ... I don't see it in my CI-builds with Visual C++ ...

Could you run the build with increased verbosity level? E.g. set this CMake-variable: https://cmake.org/cmake/help/v3.18/variable/CMAKE_VERBOSE_MAKEFILE.html

Also the compiler seems to ignore the -G-option and this seems to be interpreted as a WARNING only ... but there is no error message, why the build/link actually fails ... at least I didn't find any ...

Best,
JAN

**Comment by jkriege2** [comment]
HI @certik !

any news on this?

**Comment by certik** [comment]
Hi @jkriege2 unfortunately I don't have time to debug this right now. I'll be happy to add you to the conda-forge as a maintainer, so that you can debug this yourself if you are interested.

**Comment by jkriege2** [comment]
Hi @certik !

sorry, I won't have time at the moment to take over your conda-build ... but I looked a bit into what you're doing:

The error from the report above seems to be that an open "-G=" appears to cl.exe, which it does not know. Maybe it was still OK with VS2015, but is no longer with your switch to VS2017?

This option is explicitly added here:
https://github.com/conda-forge/jkqtplotter-feedstock/blob/78ea4b278a84334a3cfb4bca11a7688d2706a6be/recipe/bld.bat

Best,
JAN

PS: Should I leave this Issue open, or is that  more a problem of the build-process/setup over at Conda, because, generally JKQtPlotter builds just fine with VS (using CMake)?

Best,
JAN

**Comment by certik** [comment]
Keep it open for a while, I'll try your suggestion, it's probably a simple thing.

**Comment by jkriege2** [comment]
Is this still relevant?

**Comment by certik** [comment]
It's still relevant, but I don't have the time to work on it. You can go ahead and close it as "won't fix".
