### ISSUE TITLE
Optional plot painter

### ISSUE THREAD

**Issue by mearex** [jkriege2/JKQtPlotter#89]
Hi!

Truly amazing plotting library! But I run into quite a significant slowdown when I tried to plot large data sets (500k and above). I have incorporated some optimization algorithm (Qwt-like, to reduce data set size), but looks like it is not enough. Is it possible to use OpenGL acceleration for such cases?
As I can see, there is JKQTPEnhancedPainter a QPainter wrapper which adds nothing new. I think it would be great to try QNanoPainter instead but it seems that in some modules original QPainter is used (not JKQTPEnhancedPainter). How do you think - how difficult to implement additional painter?

Regards,
Alex

**Comment by sim186** [comment]
Hi, I also some times ago experienced similar issue might be interesting read the issue I opened (https://github.com/jkriege2/JKQtPlotter/issues/84). As Jan suggested enabling some option for me did the job (+ applied was is described in the linked issue), in particular to speed-up the drawing for very large dataset I enabled (fine tine the input based on your needs):
```
setUseNonvisibleLineCompression(true)
setNonvisibleLineCompressionAgressiveness(8.0)
```

**Comment by jkriege2** [comment]
Hi!
sorry for the delay in answering ... since the speedup-tips have already been given, I will answer to the QPainter-replacement:

This would seem possible (although not easily, since QPainter does not have a virtual interface that can be easily extended or reimmplemented), but not wiht the QNanoPainter you proposed: JKQTPlotter currently depends on the QPainter API and also its capabilities e.g. in font rendering. So if you find a faster painter that offers these capabilities this would be possible with the current  ode base ... although some kind of commposition scheme is required to make the painters exchangeable without a base class.

Best,
JAN

PS: I will keep this open a bit longer, so we can discuss
